const pageContent = document.getElementById('pageContent');
const sidebar = document.getElementById('sidebar');
const modal = document.getElementById('recordModal');
const modalTitle = document.getElementById('modalTitle');
const modalEyebrow = document.getElementById('modalEyebrow');
const modalBody = document.getElementById('modalBody');
const toast = document.getElementById('toast');

const readinessItems = [
  {id:1, requirement:'Equipment installation', category:'Equipment', owner:'Technical Team', mandatory:true, evidence:'Installation report', status:'Complete', remarks:'All major equipment installed and tested.'},
  {id:2, requirement:'POS installation and testing', category:'Systems', owner:'IT Team', mandatory:true, evidence:'Test confirmation', status:'In Progress', remarks:'Terminal installed; final transaction test pending.'},
  {id:3, requirement:'Facility preparation', category:'Facility', owner:'Contractor', mandatory:true, evidence:'Inspection photos', status:'Complete', remarks:'Dining, counter, utilities, and sanitation areas cleared.'},
  {id:4, requirement:'Certified crew assignment', category:'Staffing', owner:'Store Trainer', mandatory:true, evidence:'Certification roster', status:'Pending', remarks:'One service crew member is still awaiting final certification.'},
  {id:5, requirement:'Initial supply delivery confirmation', category:'Logistics', owner:'Logistics Team', mandatory:false, evidence:'Delivery receipt', status:'Complete', remarks:'Initial supplies delivered and acknowledged.'},
  {id:6, requirement:'Exterior signage installation', category:'Facility', owner:'Contractor', mandatory:true, evidence:'Completion photo', status:'Pending', remarks:'Installation scheduled for July 22.'}
];

const tasks = [
  {id:1, task:'Complete final POS transaction test', category:'Systems', owner:'IT Team', due:'Today', priority:'High', status:'In Progress'},
  {id:2, task:'Upload certified crew roster', category:'Staffing', owner:'Store Trainer', due:'Today', priority:'High', status:'Pending'},
  {id:3, task:'Install exterior branch signage', category:'Facility', owner:'Contractor', due:'Jul 22', priority:'Medium', status:'Pending'},
  {id:4, task:'Confirm utilities and internet stability', category:'Facility', owner:'Store Manager', due:'Jul 22', priority:'Medium', status:'Complete'},
  {id:5, task:'Prepare opening-day coordination brief', category:'Operations', owner:'Store Manager', due:'Jul 23', priority:'Low', status:'In Progress'}
];

const issues = [
  {id:1, title:'POS activation delayed', category:'Systems', owner:'IT Team', priority:'Critical', reported:'Jul 21, 9:10 AM', status:'In Progress', details:'Activation credentials have not yet been released.'},
  {id:2, title:'Exterior signage installation delayed', category:'Facility', owner:'Contractor', priority:'High', reported:'Jul 20, 3:30 PM', status:'Open', details:'Installer rescheduled due to material delivery delay.'},
  {id:3, title:'Air-conditioning test produced abnormal noise', category:'Equipment', owner:'Technical Team', priority:'Medium', reported:'Jul 19, 11:40 AM', status:'Resolved', details:'Loose panel was secured and the unit was retested.'}
];

let branchStage = 'pre-launch';
let clearanceStatus = 'Not Yet Submitted';
let activeSection = 'overview';
let activeModal = null;

const icon = name => `<i data-lucide="${name}"></i>`;
const statusClass = status => ({Complete:'strong',Resolved:'strong',Approved:'strong','In Progress':'good',Pending:'attention',Open:'attention',Submitted:'good'}[status] || 'attention');
const priorityClass = priority => ({Critical:'high',High:'high',Medium:'medium',Low:'low'}[priority] || 'medium');
const readinessPercent = () => Math.round(readinessItems.filter(item => item.status === 'Complete').length / readinessItems.length * 100);
const mandatoryComplete = () => readinessItems.filter(item => item.mandatory && item.status === 'Complete').length;
const mandatoryTotal = () => readinessItems.filter(item => item.mandatory).length;
const openIssues = () => issues.filter(issue => issue.status !== 'Resolved');
const canRequestClearance = () => mandatoryComplete() === mandatoryTotal() && !issues.some(issue => issue.priority === 'Critical' && issue.status !== 'Resolved');

function initIcons(){ if(window.lucide) lucide.createIcons(); }
function showToast(message){ toast.querySelector('span').textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function updateBadges(){ document.getElementById('readinessBadge').textContent = readinessItems.filter(item => item.status !== 'Complete').length; document.getElementById('issueBadge').textContent = openIssues().length; }
function header(eyebrow, title, description, action=''){ return `<div class="welcome-row"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${description}</p></div>${action}</div>`; }

function overviewTemplate(){
  const percent = readinessPercent();
  return `${header('PASIG CAPITOL • LAUNCH PREPARATION','Good morning, Ruth!','Monitor branch readiness, resolve launch issues, and prepare the store for opening.','<div class="date-control">'+icon('calendar-days')+'<span>July 21, 2026</span></div>')}
  <div class="alert-banner"><div class="alert-icon">${icon('triangle-alert')}</div><div><strong>${readinessItems.filter(i=>i.status!=='Complete').length} launch requirements still need attention</strong><span>Complete all mandatory requirements and resolve critical issues before requesting opening clearance.</span></div><button data-open-section="readiness">Review readiness ${icon('arrow-right')}</button></div>
  <div class="stats-grid">
    <article class="stat-card"><div class="stat-icon green">${icon('clipboard-check')}</div><div><span>Launch Readiness</span><strong>${percent}%</strong><small><b>${readinessItems.filter(i=>i.status==='Complete').length} of ${readinessItems.length}</b> requirements complete</small></div></article>
    <article class="stat-card"><div class="stat-icon yellow">${icon('list-checks')}</div><div><span>Remaining Tasks</span><strong>${tasks.filter(t=>t.status!=='Complete').length}</strong><small>${tasks.filter(t=>t.priority==='High'&&t.status!=='Complete').length} high-priority tasks</small></div></article>
    <article class="stat-card"><div class="stat-icon orange">${icon('triangle-alert')}</div><div><span>Open Issues</span><strong>${openIssues().length}</strong><small>${issues.filter(i=>i.priority==='Critical'&&i.status!=='Resolved').length} critical issue</small></div></article>
    <article class="stat-card"><div class="stat-icon red">${icon('badge-check')}</div><div><span>Clearance Status</span><strong style="font-size:1.35rem">${clearanceStatus}</strong><small>${canRequestClearance()?'Ready for submission':'Requirements incomplete'}</small></div></article>
  </div>
  <div class="dashboard-grid">
    <section class="panel branch-panel"><div class="panel-heading"><div><h2>Launch Timeline</h2><p>Current progress toward opening approval</p></div><button class="text-btn" data-open-section="clearance">View clearance ${icon('arrow-up-right')}</button></div><div class="branch-list">
      ${['Site turnover|Complete','Equipment installation|Complete','Certified staff assignment|Pending','Final facility verification|In Progress','Opening clearance|'+clearanceStatus].map((entry,index)=>{const [name,status]=entry.split('|');return `<article class="branch-row" data-search="${name} ${status}"><div class="branch-rank">${status==='Complete'?icon('check'):index+1}</div><div class="branch-name"><strong>${name}</strong><span>${status==='Complete'?'Verified and recorded':'Requires follow-up before opening'}</span></div><span class="status ${statusClass(status)}">${status}</span></article>`}).join('')}
    </div></section>
    <section class="panel activity-panel"><div class="panel-heading"><div><h2>Today's Priorities</h2><p>Tasks that may affect the opening schedule</p></div><button class="text-btn" data-open-section="tasks">View all ${icon('arrow-right')}</button></div><div class="timeline">
      ${tasks.filter(t=>t.status!=='Complete').slice(0,4).map(t=>`<div class="timeline-item" data-search="${t.task} ${t.owner}"><span class="dot ${t.priority==='High'?'red':'yellow'}">${icon(t.priority==='High'?'alert-circle':'clock-3')}</span><div><strong>${t.task}</strong><p>${t.owner} • ${t.status}</p><small>Due ${t.due}</small></div></div>`).join('')}
    </div></section>
  </div>
  <section class="panel incident-panel"><div class="panel-heading"><div><h2>Launch Issues Requiring Attention</h2><p>Coordinate with responsible teams and track each issue until resolved</p></div><button class="text-btn" data-open-section="issues">View issue register ${icon('arrow-right')}</button></div>${issueTable(openIssues().slice(0,3))}</section>`;
}

function readinessTemplate(){ return `${header('PRE-OPENING CHECKLIST','Launch Readiness','Verify equipment, systems, facilities, staffing, and other branch requirements.','<button class="primary-btn" data-add-readiness>'+icon('plus')+' Add Requirement</button>')}
<div class="stats-grid"><article class="stat-card"><div class="stat-icon green">${icon('circle-check-big')}</div><div><span>Overall Completion</span><strong>${readinessPercent()}%</strong><small>${readinessItems.filter(i=>i.status==='Complete').length} requirements verified</small></div></article><article class="stat-card"><div class="stat-icon yellow">${icon('asterisk')}</div><div><span>Mandatory Complete</span><strong>${mandatoryComplete()}<span>/${mandatoryTotal()}</span></strong><small>Required before clearance</small></div></article><article class="stat-card"><div class="stat-icon orange">${icon('clock-3')}</div><div><span>Pending Verification</span><strong>${readinessItems.filter(i=>i.status!=='Complete').length}</strong><small>Needs status or evidence</small></div></article><article class="stat-card"><div class="stat-icon red">${icon('shield-alert')}</div><div><span>Critical Blockers</span><strong>${issues.filter(i=>i.priority==='Critical'&&i.status!=='Resolved').length}</strong><small>Must be resolved first</small></div></article></div>
<section class="panel"><div class="panel-heading"><div><h2>Digital Pre-Opening Checklist</h2><p>Update requirement status, evidence, and remarks</p></div></div><div class="table-wrap"><table><thead><tr><th>Requirement</th><th>Category</th><th>Responsible Team</th><th>Evidence</th><th>Status</th><th></th></tr></thead><tbody>${readinessItems.map(item=>`<tr data-search="${item.requirement} ${item.category} ${item.owner} ${item.status}"><td><strong>${item.requirement}</strong><span>${item.mandatory?'Mandatory requirement':'Supporting requirement'}</span></td><td>${item.category}</td><td>${item.owner}</td><td>${item.evidence}</td><td><span class="table-status ${statusClass(item.status)}">${item.status}</span></td><td><button class="review-btn" data-edit-readiness="${item.id}">Update</button></td></tr>`).join('')}</tbody></table></div></section>`; }

function tasksTemplate(){ return `${header('LAUNCH COORDINATION','Readiness Tasks','Track preparation activities, assigned teams, due dates, and completion progress.','<button class="primary-btn" data-add-task>'+icon('plus')+' Add Task</button>')}<section class="panel"><div class="panel-heading"><div><h2>Assigned Launch Tasks</h2><p>Coordinate work without replacing specialist team systems</p></div></div><div class="table-wrap"><table><thead><tr><th>Task</th><th>Category</th><th>Owner</th><th>Due</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>${tasks.map(task=>`<tr data-search="${task.task} ${task.category} ${task.owner} ${task.status}"><td><strong>${task.task}</strong><span>Task #SM-${String(task.id).padStart(3,'0')}</span></td><td>${task.category}</td><td>${task.owner}</td><td>${task.due}</td><td><span class="priority ${priorityClass(task.priority)}">${task.priority}</span></td><td><span class="table-status ${statusClass(task.status)}">${task.status}</span></td><td><button class="review-btn" data-edit-task="${task.id}">Update</button></td></tr>`).join('')}</tbody></table></div></section>`; }

function issueTable(list){ return `<div class="table-wrap"><table><thead><tr><th>Issue</th><th>Category</th><th>Responsible Team</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>${list.map(issue=>`<tr data-search="${issue.title} ${issue.category} ${issue.owner} ${issue.status}"><td><strong>${issue.title}</strong><span>${issue.reported}</span></td><td>${issue.category}</td><td>${issue.owner}</td><td><span class="priority ${priorityClass(issue.priority)}">${issue.priority}</span></td><td><span class="table-status ${statusClass(issue.status)}">${issue.status}</span></td><td><button class="review-btn" data-edit-issue="${issue.id}">Update</button></td></tr>`).join('')}</tbody></table></div>`; }
function issuesTemplate(){ return `${header('ISSUE RESOLUTION','Launch Issues','Report launch blockers, assign follow-ups, and monitor resolution before opening.','<button class="primary-btn" data-add-issue>'+icon('plus')+' Report Issue</button>')}<div class="alert-banner"><div class="alert-icon">${icon('shield-alert')}</div><div><strong>${openIssues().length} unresolved launch issues</strong><span>Critical issues prevent the opening clearance request from being submitted.</span></div></div><section class="panel"><div class="panel-heading"><div><h2>Launch Issue Register</h2><p>Open, monitored, and resolved pre-opening concerns</p></div></div>${issueTable(issues)}</section>`; }

function clearanceTemplate(){ const allowed=canRequestClearance(); return `${header('FINAL APPROVAL','Opening Clearance','Review the readiness summary and submit the branch for opening approval.','')}
<div class="stats-grid"><article class="stat-card"><div class="stat-icon green">${icon('wrench')}</div><div><span>Equipment & Systems</span><strong>${Math.round(readinessItems.filter(i=>['Equipment','Systems'].includes(i.category)&&i.status==='Complete').length/readinessItems.filter(i=>['Equipment','Systems'].includes(i.category)).length*100)}%</strong><small>Installation and testing</small></div></article><article class="stat-card"><div class="stat-icon yellow">${icon('building-2')}</div><div><span>Facility</span><strong>${Math.round(readinessItems.filter(i=>i.category==='Facility'&&i.status==='Complete').length/readinessItems.filter(i=>i.category==='Facility').length*100)}%</strong><small>Preparation and signage</small></div></article><article class="stat-card"><div class="stat-icon orange">${icon('users')}</div><div><span>Staffing</span><strong>${Math.round(readinessItems.filter(i=>i.category==='Staffing'&&i.status==='Complete').length/Math.max(1,readinessItems.filter(i=>i.category==='Staffing').length)*100)}%</strong><small>Certified crew assignment</small></div></article><article class="stat-card"><div class="stat-icon red">${icon('triangle-alert')}</div><div><span>Unresolved Issues</span><strong>${openIssues().length}</strong><small>${issues.filter(i=>i.priority==='Critical'&&i.status!=='Resolved').length} critical blocker</small></div></article></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Clearance Validation</h2><p>Requirements checked automatically by the prototype</p></div></div><div class="branch-list"><article class="branch-row"><div class="branch-rank">${mandatoryComplete()===mandatoryTotal()?icon('check'):icon('x')}</div><div class="branch-name"><strong>Mandatory requirements completed</strong><span>${mandatoryComplete()} of ${mandatoryTotal()} verified</span></div><span class="status ${mandatoryComplete()===mandatoryTotal()?'strong':'attention'}">${mandatoryComplete()===mandatoryTotal()?'Passed':'Incomplete'}</span></article><article class="branch-row"><div class="branch-rank">${!issues.some(i=>i.priority==='Critical'&&i.status!=='Resolved')?icon('check'):icon('x')}</div><div class="branch-name"><strong>No unresolved critical issue</strong><span>Critical launch blockers must be closed</span></div><span class="status ${!issues.some(i=>i.priority==='Critical'&&i.status!=='Resolved')?'strong':'attention'}">${!issues.some(i=>i.priority==='Critical'&&i.status!=='Resolved')?'Passed':'Blocked'}</span></article><article class="branch-row"><div class="branch-rank">${icon('file-check-2')}</div><div class="branch-name"><strong>Readiness summary generated</strong><span>Checklist, evidence, issues, and responsible teams included</span></div><span class="status strong">Ready</span></article></div></section><section class="panel"><div class="panel-heading"><div><h2>Opening Clearance Request</h2><p>Submit once all validation requirements pass</p></div></div><div class="settings-form"><label>Current Status</label><input value="${clearanceStatus}" disabled><label>Proposed Opening Date</label><input type="date" value="2026-07-25"><label>Store Manager Remarks</label><textarea id="clearanceRemarks" rows="5" placeholder="Add a short readiness summary..."></textarea><button class="primary-btn" id="requestClearance" ${!allowed||clearanceStatus!=='Not Yet Submitted'?'disabled':''}>${icon('send')} ${clearanceStatus==='Not Yet Submitted'?'Request Opening Clearance':'Request Submitted'}</button>${!allowed?'<small>Complete all mandatory requirements and resolve critical issues to enable submission.</small>':''}</div></section></div>`; }

function postLaunchTemplate(){ const locked=branchStage!=='post-launch'; return `${header('AFTER OPENING','Post-Launch Reports','Submit operational information required by the Area Manager without duplicating POS or ERP functions.','')}${locked?`<div class="alert-banner"><div class="alert-icon">${icon('lock-keyhole')}</div><div><strong>Post-launch reporting is currently locked</strong><span>This section becomes available after opening clearance is approved.</span></div><button data-demo-open>Preview Mode</button></div>`:''}<div class="stats-grid"><article class="stat-card"><div class="stat-icon green">${icon('file-text')}</div><div><span>Daily Operations Report</span><strong>${locked?'Locked':'Draft'}</strong><small>Submit branch operational summary</small></div></article><article class="stat-card"><div class="stat-icon yellow">${icon('notebook-tabs')}</div><div><span>Operational Log</span><strong>${locked?'—':'3'}</strong><small>Today’s recorded updates</small></div></article><article class="stat-card"><div class="stat-icon orange">${icon('triangle-alert')}</div><div><span>Incident Reports</span><strong>${locked?'—':'1'}</strong><small>Operational issues sent upward</small></div></article><article class="stat-card"><div class="stat-icon red">${icon('clipboard-list')}</div><div><span>Corrective Actions</span><strong>${locked?'—':'2'}</strong><small>Assigned by Area Manager</small></div></article></div><section class="panel"><div class="panel-heading"><div><h2>Reporting Actions</h2><p>Lightweight workflows connected to Area Manager review</p></div></div><div class="branch-list">${[['Daily Operations Report','Summarize compliance, service concerns, and operational notes','file-up'],['Operational Log','Record meaningful daily branch updates','notebook-pen'],['Incident Report','Escalate equipment, staffing, customer, or supply issues','triangle-alert'],['Corrective Actions','View and update tasks assigned by the Area Manager','clipboard-check']].map((item,index)=>`<article class="branch-row"><div class="branch-rank">${icon(item[2])}</div><div class="branch-name"><strong>${item[0]}</strong><span>${item[1]}</span></div><button class="review-btn" data-post-action="${index}" ${locked?'disabled':''}>${index===3?'View':'Open'}</button></article>`).join('')}</div></section>`; }

function settingsTemplate(){ return `${header('ACCOUNT PREFERENCES','Settings','Manage Ruth Torres’s Store Manager dashboard preferences.','')}<div class="settings-grid"><section class="panel settings-card"><div class="panel-heading"><div><h2>Profile Information</h2><p>Displayed in readiness and clearance records</p></div></div><div class="settings-form"><label>Full Name</label><input value="Ruth Torres"><label>Role</label><input value="Store Manager" disabled><label>Assigned Branch</label><input value="Pasig Capitol" disabled><label>Email Address</label><input value="ruth.torres@5joys.com"><button class="primary-btn compact save-settings">Save Changes</button></div></section><section class="panel settings-card"><div class="panel-heading"><div><h2>Notifications</h2><p>Select the launch updates you want to receive</p></div></div><div class="settings-form toggles"><label><input type="checkbox" checked> Pending and overdue readiness tasks</label><label><input type="checkbox" checked> Critical launch issue alerts</label><label><input type="checkbox" checked> Staff certification updates</label><label><input type="checkbox" checked> Opening clearance decisions</label><label><input type="checkbox"> Daily launch summary email</label><button class="primary-btn compact save-settings">Update Preferences</button></div></section></div>`; }

const templates = {overview:overviewTemplate, readiness:readinessTemplate, tasks:tasksTemplate, issues:issuesTemplate, clearance:clearanceTemplate, postlaunch:postLaunchTemplate, settings:settingsTemplate};
function renderSection(section=activeSection){ activeSection=section; pageContent.innerHTML=templates[section](); pageContent.dataset.currentSection=section; updateBadges(); initIcons(); applySearch(document.getElementById('globalSearch').value); window.scrollTo({top:0,behavior:'smooth'}); }

function modalFields(type, data={}){
  if(type==='readiness') return `<label>Requirement</label><input id="modalName" value="${data.requirement||''}" ${data.id?'disabled':''}><label>Status</label><select id="modalStatus"><option ${data.status==='Pending'?'selected':''}>Pending</option><option ${data.status==='In Progress'?'selected':''}>In Progress</option><option ${data.status==='Complete'?'selected':''}>Complete</option></select><label>Evidence / Verification</label><input id="modalEvidence" value="${data.evidence||''}" placeholder="e.g., Completion photo"><label>Remarks</label><textarea id="modalRemarks" rows="4">${data.remarks||''}</textarea>`;
  if(type==='task') return `<label>Task</label><input id="modalName" value="${data.task||''}"><label>Owner</label><input id="modalOwner" value="${data.owner||''}"><label>Status</label><select id="modalStatus"><option ${data.status==='Pending'?'selected':''}>Pending</option><option ${data.status==='In Progress'?'selected':''}>In Progress</option><option ${data.status==='Complete'?'selected':''}>Complete</option></select><label>Priority</label><select id="modalPriority"><option ${data.priority==='Low'?'selected':''}>Low</option><option ${data.priority==='Medium'?'selected':''}>Medium</option><option ${data.priority==='High'?'selected':''}>High</option></select>`;
  if(type==='issue') return `<label>Issue</label><input id="modalName" value="${data.title||''}"><label>Responsible Team</label><input id="modalOwner" value="${data.owner||''}"><label>Priority</label><select id="modalPriority"><option ${data.priority==='Medium'?'selected':''}>Medium</option><option ${data.priority==='High'?'selected':''}>High</option><option ${data.priority==='Critical'?'selected':''}>Critical</option></select><label>Status</label><select id="modalStatus"><option ${data.status==='Open'?'selected':''}>Open</option><option ${data.status==='In Progress'?'selected':''}>In Progress</option><option ${data.status==='Resolved'?'selected':''}>Resolved</option></select><label>Resolution Notes</label><textarea id="modalRemarks" rows="4">${data.details||''}</textarea>`;
  return `<label>Report Type</label><input value="${data.name||'Operational Report'}" disabled><label>Operational Summary</label><textarea id="modalRemarks" rows="6" placeholder="Enter the information to be submitted to the Area Manager..."></textarea>`;
}
function openModal(type, id=null, title='Update Record'){ const collection={readiness:readinessItems,task:tasks,issue:issues}[type]; const data=collection&&id?collection.find(item=>item.id===id):{}; activeModal={type,id}; modalEyebrow.textContent=type==='report'?'POST-LAUNCH REPORT':'STORE UPDATE'; modalTitle.textContent=title; modalBody.innerHTML=modalFields(type,data); modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); initIcons(); }
function closeModal(){ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); activeModal=null; }
function saveModal(){ if(!activeModal)return; const {type,id}=activeModal; const name=document.getElementById('modalName')?.value.trim(); const status=document.getElementById('modalStatus')?.value; const owner=document.getElementById('modalOwner')?.value.trim(); const priority=document.getElementById('modalPriority')?.value; const remarks=document.getElementById('modalRemarks')?.value.trim();
  if(type==='readiness'){ if(id){const item=readinessItems.find(i=>i.id===id); item.status=status; item.evidence=document.getElementById('modalEvidence').value.trim(); item.remarks=remarks;} else readinessItems.push({id:Date.now(),requirement:name||'New requirement',category:'Other',owner:'Store Manager',mandatory:false,evidence:document.getElementById('modalEvidence').value.trim()||'Pending evidence',status,remarks}); }
  if(type==='task'){ if(id){const item=tasks.find(i=>i.id===id); item.task=name; item.owner=owner; item.status=status; item.priority=priority;} else tasks.push({id:Date.now(),task:name||'New readiness task',category:'Operations',owner:owner||'Store Manager',due:'TBD',priority,status}); }
  if(type==='issue'){ if(id){const item=issues.find(i=>i.id===id); item.title=name; item.owner=owner; item.status=status; item.priority=priority; item.details=remarks;} else issues.push({id:Date.now(),title:name||'New launch issue',category:'Other',owner:owner||'Store Manager',priority,status,reported:'Just now',details:remarks}); }
  closeModal(); renderSection(); showToast(type==='report'?'Report saved successfully.':'Store update saved successfully.'); }

function applySearch(value){ const query=value.trim().toLowerCase(); document.querySelectorAll('[data-search]').forEach(item=>item.classList.toggle('hidden-by-search',query&&!item.dataset.search.toLowerCase().includes(query))); }

document.getElementById('menuBtn').addEventListener('click',()=>sidebar.classList.toggle('open'));
document.querySelectorAll('.nav-item[data-section]').forEach(item=>item.addEventListener('click',()=>{document.querySelectorAll('.nav-item[data-section]').forEach(nav=>nav.classList.remove('active'));item.classList.add('active');sidebar.classList.remove('open');renderSection(item.dataset.section);}));
document.addEventListener('click',event=>{
  const opener=event.target.closest('[data-open-section]'); if(opener){document.querySelector(`.nav-item[data-section="${opener.dataset.openSection}"]`)?.click();return;}
  const editReadiness=event.target.closest('[data-edit-readiness]'); if(editReadiness){openModal('readiness',Number(editReadiness.dataset.editReadiness),'Update Readiness Requirement');return;}
  const editTask=event.target.closest('[data-edit-task]'); if(editTask){openModal('task',Number(editTask.dataset.editTask),'Update Readiness Task');return;}
  const editIssue=event.target.closest('[data-edit-issue]'); if(editIssue){openModal('issue',Number(editIssue.dataset.editIssue),'Update Launch Issue');return;}
  if(event.target.closest('[data-add-readiness]')){openModal('readiness',null,'Add Readiness Requirement');return;}
  if(event.target.closest('[data-add-task]')){openModal('task',null,'Add Readiness Task');return;}
  if(event.target.closest('[data-add-issue]')){openModal('issue',null,'Report Launch Issue');return;}
  const postAction=event.target.closest('[data-post-action]'); if(postAction){const names=['Daily Operations Report','Operational Log','Incident Report','Corrective Actions'];openModal('report',null,names[Number(postAction.dataset.postAction)]);return;}
  if(event.target.closest('#requestClearance')){clearanceStatus='Submitted';renderSection('clearance');showToast('Opening clearance request submitted for review.');return;}
  if(event.target.closest('[data-demo-open]')){branchStage='post-launch';renderSection('postlaunch');showToast('Post-launch preview mode enabled.');return;}
  if(event.target.closest('.save-settings'))showToast('Settings updated successfully.');
});
document.getElementById('closeModal').addEventListener('click',closeModal);
document.getElementById('cancelModal').addEventListener('click',closeModal);
document.getElementById('saveModal').addEventListener('click',saveModal);
modal.addEventListener('click',event=>{if(event.target===modal)closeModal();});
document.getElementById('globalSearch').addEventListener('input',event=>applySearch(event.target.value));
document.getElementById('logoutBtn').addEventListener('click',()=>{localStorage.removeItem('b2bUserRole');localStorage.removeItem('b2bUserName');window.location.href='index.html';});
renderSection('overview');
